# Generated by Django 2.1 on 2020-12-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20201228_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Complete time'),
        ),
        migrations.AddField(
            model_name='card',
            name='expected_effort',
            field=models.FloatField(blank=True, default=1, verbose_name='Expected effort'),
        ),
        migrations.AddField(
            model_name='card',
            name='real_effort',
            field=models.FloatField(blank=True, null=True, verbose_name='Real effort'),
        ),
        migrations.AddField(
            model_name='card',
            name='task_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Complete', 'Complete'), ('Archived', 'Archived')], default='Pending', max_length=8, verbose_name='State'),
        ),
    ]
