# Generated by Django 2.1 on 2021-01-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20201230_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='board',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
